name: cookbook_exercises
description: Flutter cookbook exercises project
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_package:
    path: ./awesome_package
  flutter:
    sdk: flutter
  sembast: ^3.2.0
  sembast_web: 2.4.0+4
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.3.4+4
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  provider: ^6.1.2
  path_provider: ^2.0.11
  shared_preferences: ^2.4.0
  http: ^1.3.0
  web_socket_channel: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic

